namespace: api-app-local-namespace
environment: development

apiApp:
  image:
    repository: ryosantouchh/api-app
    tag: dev
    pullPolicy: Always
  replicas: 1
  port: 3000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
  ingress:
    enabled: true
    className: nginx
    host: api.local
  config:
    NODE_ENV: development
    PORT: "3000"

rustfs:
  image:
    repository: rustfs/rustfs
    tag: latest
    pullPolicy: IfNotPresent
  storage: 5Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  ingress:
    enabled: true
    className: nginx
    host: s3.local

postgres:
  image:
    repository: postgres:15
    tag: 15
    pullPolicy: IfNotPresent
  storage: 5Gi
  ingress:
    enabled: true
    className: nginx
    host: db.local

