global:
  namespace: api-app-local-namespace
  environment: development

api-app:
  namespace: api-app-local-namespace
  environment: development
  image:
    repository: ryosantouchh/tsoa-poc-api-app
    tag: dev
    pullPolicy: Always
  ingress:
    enabled: true
    className: traefik
    host: api.quantlab
  config:
    NODE_ENV: development

postgres:
  namespace: api-app-local-namespace

rustfs:
  namespace: api-app-local-namespace
  ingress:
    enabled: true
    className: traefik
    host: s3.quantlab
