namespace: api-app-local-namespace
environment: development

apiApp:
  image:
    tag: dev
    pullPolicy: Always
  ingress:
    enabled: true
    host: api.localhost
  config:
    NODE_ENV: development
