apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.apiApp.config.NODE_ENV | quote }}
  PORT: {{ .Values.apiApp.config.PORT | quote }}
