apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.apiApp.secret.databaseUrl | quote }}
  S3_ENDPOINT: {{ .Values.apiApp.secret.s3Endpoint | quote }}
  S3_ACCESS_KEY: {{ .Values.apiApp.secret.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.apiApp.secret.s3SecretKey | quote }}
