apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-app-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      terminationGracePeriodSeconds: 30
      containers:
        - name: api-app-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: {{ .Values.port }}
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: {{ .Values.port }}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   failureThreshold: 3
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   readOnlyRootFilesystem: true
          #   capabilities:
          #     drop: ["ALL"]
