apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rustfs-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  RUSTFS_ROOT_USER: {{ .Values.rustfs.secret.accessKey | quote }}
  RUSTFS_ROOT_PASSWORD: {{ .Values.rustfs.secret.secretKey | quote }}
