apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ .Values.rustfs.secret.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.rustfs.secret.secretKey | quote }}
