apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rustfs-headless
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-rustfs
  ports:
    - name: api
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
    - name: console
      port: {{ .Values.consolePort }}
      targetPort: {{ .Values.consolePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rustfs-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-rustfs
  ports:
    - name: api
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
    - name: console
      port: {{ .Values.consolePort }}
      targetPort: {{ .Values.consolePort }}
  type: ClusterIP
