version: "3.8"
services:
  db:
    image: postgres:15
    container_name: tsoa-starter-template-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tsoa-starter-template-db
    ports:
      - "5432:5432"
    volumes:
      - tsoa-starter-template-volume:/var/lib/postgresql/data

  # s3:
  #   image: quay.io/minio/minio
  #   container_name: tsoa-starter-template-minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: password
  #   volumes:
  #     - tsoa-starter-template-volume:/data
  #   command: server /data --console-address ":9001"

volumes:
  tsoa-starter-template-volume:
