version: "3.8"
services:
  db:
    image: postgres:15
    container_name: tsoa-starter-template-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tsoa-starter-template-db
    ports:
      - "5432:5432"
    volumes:
      - tsoa-starter-template-db-volume:/var/lib/postgresql/data

  s3:
    image: rustfs/rustfs:latest
    container_name: tsoa-starter-template-rustfs
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: password
    volumes:
      - tsoa-starter-template-s3-volume:/data
    command: /data

volumes:
  tsoa-starter-template-db-volume:
  tsoa-starter-template-s3-volume:
