apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.secret.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.secret.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.password | quote }}
